visual_input_size: 1026
sub_input_size: 770
query_input_size: 768
hidden_size: 384
conv_kernel_size: 5
conv_stride: 1
max_ctx_l: 128
max_desc_l: 30
input_drop: 0.1
drop: 0.1
n_heads: 8
initializer_range: 0.02
ctx_mode: video_sub_tef
margin: 0.1
ranking_loss_type: hinge
lw_neg_q: 1
lw_neg_ctx: 1
lw_fcl: 0.03
lw_vcl: 0.03
lw_st_ed: 0
use_hard_negative: false
hard_pool_size: 20
